server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: authority
          uri: lb://authority-service
          predicates:
            - Path=/auth/**
        - id: email
          uri: lb://email-service
          predicates:
            - Path=/email/**
  main:
    web-application-type: reactive